### ISSUE TITLE
When I copy/paste the exemple from the index.md it doesn't work

### ISSUE THREAD

**Issue by tibastral** [thebritican/elm-autocomplete#39]

**Comment by stkb** [comment]
To add some information, the readme example is missing some definitions and  is far from a complete example. However there's also a syntax error in the `Model` definition:

``` elm
type alias Model =
  { autoState = Autocomplete.State -- Own the State of the menu in your model
  , query = String -- Perhaps you want to filter by a string?
  , people = List Person -- The data you want to list and filter
  }
```

The `=`'s should be replaced with `:`'s

**Comment by gregziegan** [comment]
Sorry about the broken README example, I should have copy/pasted from examples instead of typing w/o a compiler 😅 

When `0.18` is released soon, there will be a major bump and the example will be the new `elm-autocomplete` and this highly customizable API will belong in https://github.com/thebritican/elm-menu.

I'll fix this README now though :)

**Comment by gregziegan** [comment]
See 933aaac8033497795b01a9d66bf0e0a94801ffd4
