### ISSUE TITLE
Port to 0.18

### ISSUE THREAD

**Issue by danstn** [thebritican/elm-autocomplete#43]
Would be great to have this ported to 0.18. 

[Migration guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md)

**Comment by gregziegan** [comment]
working on this in the branch https://github.com/thebritican/elm-autocomplete/tree/drop-in

Goal is a slightly modified API that's much more drop-in. Pretty much the exact same API will be available in `elm-menu`. Still testing it (elm-menu) in this branch. This will hopefully all be done by the end of the week!

**Comment by gregziegan** [comment]
Autocomplete now works with a smaller API :) Still need to document and make some more configuration functions that reduce boilerplate. I just released a patch update for 0.18 so I can close this. It's taking a little longer than expected because I don't want anyone to have to wire up more than one subscription for keyboard input anymore w/ `elm-menu`. As seen in #37 

The idea: make only one menu controllable via keyboard input at a time. It would be silly to have a UI that does something otherwise! This requires some revamping to the menu, but the API should be _mostly_ similar to the current `elm-autocomplete`
